name: Issue Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    labels: [check]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            Bryancdi
          numOfAssignee: 1
    - name: 'Auto-assign pull request'
      uses: bobheadxi/auto-assign@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            ERP-Modular/admin_role
          numOfAssignee: 1