name: Build project

on:
  pull_request:
    types: [labeled]
    labels: [check]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: echo "hello world!"; ls -la