name: Build project

on:
  pull_request:
    types: [labeled]
    labels: [check]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git clone git@github.com:ERP-Modular/cicd_utils.git
            echo "hello world!"; ls -la